### ISSUE TITLE
Cant see the node

### ISSUE THREAD

**Issue by ai-rtist** [ShmuelRonen/ComfyUI_wav2lip#17]
The cmd:

Starting server
To see the GUI go to: http://127.0.0.1:8188
To see the GUI go to: https://127.0.0.1:8189
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
# 😺dzNodes: LayerStyle -> Warning: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
#read_workflow_json_files_all C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
# 😺dzNodes: LayerStyle -> Warning: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
#read_workflow_json_files_all C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\

**Comment by ai-rtist** [comment]
I correct this deleting ".exemple" from "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini.exemple"

But now:

Starting server
To see the GUI go to: http://127.0.0.1:8188
To see the GUI go to: https://127.0.0.1:8189
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
#read_workflow_json_files_all C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
        Loading CodeFormer: codeformer.pth
(80, 5880)
Length of mel chunks: 2201
Load model from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
Load checkpoint from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:18<00:00,  9.07s/it]
box error████████████████████████████████████████████████████████████████████████████████| 2/2 [00:18<00:00,  7.62s/it]
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
box error
  0%|                                                                                           | 0/18 [00:20<?, ?it/s]
out_images len = 0
!!! Exception during processing!!! stack expects a non-empty TensorList
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 113, in todo
    images = torch.stack(out_tensor_list, dim=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects a non-empty TensorList

Prompt executed in 24.24 seconds

**Comment by ai-rtist** [comment]
Base directory: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip
Checkpoints path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints
Model path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
Wav2Lip path added to sys.path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip
Directory created or exists: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\facedetection
Current directory: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip
Wav2Lip path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip
Using cuda for inference.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\google_translator.py", line 4, in <module>
    from googletrans import Translator
ModuleNotFoundError: No module named 'googletrans'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\google_translator.py module for custom nodes: No module named 'googletrans'

**Comment by ShmuelRonen** [comment]
This error is not related to ComfyUi_wav2lip node
