### ISSUE TITLE
How to fix load failed?

### ISSUE THREAD

**Issue by bismark211** [ShmuelRonen/ComfyUI_wav2lip#21]
2024-06-04 05:34:06,935- root:1897- WARNING- Traceback (most recent call last):
  File "E:\Comfyui\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Comfyui\ComfyUI\custom_nodes\ComfyUI_wav2lip\__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "E:\Comfyui\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 56, in <module>
    from wav2lip_node import wav2lip_
  File "E:\Comfyui\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip\wav2lip_node.py", line 5, in <module>
    from models import Wav2Lip
ImportError: cannot import name 'Wav2Lip' from 'models' (E:\Comfyui\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\__init__.py)

2024-06-04 05:34:06,936- root:1898- WARNING- Cannot import E:\Comfyui\ComfyUI\custom_nodes\ComfyUI_wav2lip module for custom nodes: cannot import name 'Wav2Lip' from 'models' (E:\Comfyui\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\__init__.py)

**Comment by ShmuelRonen** [comment]
There are a strange statement: 'cannot import name 'Wav2Lip' from 'models' (E:\Comfyui\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models_init_.py)' 

Because wav2lip node works for most of the users, maybe try to change the E:\Comfyui\ folder name to something more unique like E:\Comfyui-main\

**Comment by ksenia-portu** [comment]
@bismark211 look into this, it supposed to  fix the poblem  https://github.com/ksenia-portu/ComfyUI_wav2lip

**Comment by bismark211** [comment]
Yes, it worked for Windows 10 too! Thank you!
