### ISSUE TITLE
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'

### ISSUE THREAD

**Issue by signorinileandro** [ShmuelRonen/ComfyUI_wav2lip#3]
Traceback (most recent call last):
  File "/home/leandro/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip.py", line 15, in <module>
    from .facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from custom_nodes.facerestore_cf.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'

**Comment by ShmuelRonen** [comment]
please git pull to the last update

**Comment by signorinileandro** [comment]
Already did, still showing the same error

**Comment by ShmuelRonen** [comment]
I upload now update for wav2lip.py please check it out for cure your error

**Comment by ShmuelRonen** [comment]
Try the new fix of wav2lip.py

**Comment by ShmuelRonen** [comment]
send me the CMD log

**Comment by signorinileandro** [comment]
```
Traceback (most recent call last):
  File "/home/leandro/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip.py", line 15, in <module>
    from .facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from custom_nodes.facerestore_cf.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'

```

**Comment by ShmuelRonen** [comment]
Also check by date if wav2lip.py indeed updated

**Comment by signorinileandro** [comment]
Yes it's updated

**Comment by ShmuelRonen** [comment]
Did you downloaded all the models and put them in the right hierarchy order

**Comment by signorinileandro** [comment]
Yes, did the whole process of cloning the repository, installing requirements and downloading models again. Still same error:
`ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'`

**Comment by signorinileandro** [comment]
Replacing that file is giving me this now:
`Traceback (most recent call last):
  File "/home/leandro/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip.py", line 22, in <module>
    from wav2lip_node import wav2lip_
ModuleNotFoundError: No module named 'wav2lip_node'

Cannot import /home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip module for custom nodes: No module named 'wav2lip_node'`

**Comment by ShmuelRonen** [comment]
Add path dynamic allocation to wav2lip.py please git pull

**Comment by signorinileandro** [comment]
Do I keep the wav2lip.py you gave me? 
How do I add the dynamic path allocation?

**Comment by ShmuelRonen** [comment]
No. just replace it with the wav2lip.py file that in the repository

**Comment by signorinileandro** [comment]
`Traceback (most recent call last):
  File "/home/leandro/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip.py", line 15, in <module>
    from .facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from custom_nodes.facerestore_cf.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'`

Still same error :cry:

**Comment by ShmuelRonen** [comment]
According to the log you sent I made another change in the code of wav2lip.py please update.

**Comment by ShmuelRonen** [comment]
New wav2lip.py please update

**Comment by signorinileandro** [comment]
`(base) leandro@LeandroPC:~/ComfyUI/custom_nodes/ComfyUI_wav2lip$ git pull
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 18 (delta 9), reused 6 (delta 6), pack-reused 3
Desempaquetando objetos: 100% (18/18), 12.27 KiB | 199.00 KiB/s, listo.
Desde https://github.com/ShmuelRonen/ComfyUI_wav2lip
   746db1d..5677b55  main       -> origin/main
Actualizando 746db1d..5677b55
Fast-forward
 README.md  | 26 ++------------------------
 wav2lip.py | 28 +++++++++++++++++++++++-----
 2 files changed, 25 insertions(+), 29 deletions(-)
(base) leandro@LeandroPC:~/ComfyUI/custom_nodes/ComfyUI_wav2lip$ ^C
(base) leandro@LeandroPC:~/ComfyUI/custom_nodes/ComfyUI_wav2lip$ cd ../..
(base) leandro@LeandroPC:~/ComfyUI$ python main.py
Total VRAM 7966 MB, total RAM 15892 MB
xformers version: 0.0.25.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "/home/leandro/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/wav2lip.py", line 15, in <module>
    from .facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from custom_nodes.facerestore_cf.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'

Cannot import /home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip module for custom nodes: No module named 'custom_nodes.facerestore_cf'

Import times for custom nodes:
   0.0 seconds: /home/leandro/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /home/leandro/ComfyUI/custom_nodes/ComfyUI_wav2lip

`

**Comment by ShmuelRonen** [comment]
Please update to the last wv2lip.py

**Comment by signorinileandro** [comment]
It had an indentation error on line 218, after fixing it, it gives the same error as before

**Comment by ShmuelRonen** [comment]
Yes. thanks for let me know. you run in on Linux. I don't check it on Linux.

**Comment by ShmuelRonen** [comment]
I find the problem. please replace the file face_restoration_helper.py from the repository that in ComfyUI_wav2lip\facelib\utils

**Comment by signorinileandro** [comment]
Switched to Windows, did a clean installation
I already have that file in the utils folder
![image](https://github.com/ShmuelRonen/ComfyUI_wav2lip/assets/65788182/301f8a29-7f47-4b8b-a16f-3e6a838c7494)

**Comment by ShmuelRonen** [comment]
I chenge 3 lines in  face_restoration_helper.py. so you must replace it

**Comment by signorinileandro** [comment]
Still same error

**Comment by ShmuelRonen** [comment]
Also delete the folder __pycache__ in ComfyUI_wav2lip\facelib\utils.

**Comment by signorinileandro** [comment]
I managed to make it work. I just replaced `custom_nodes.facerestore_cf` to `custom_nodes.ComfyUI_wav2lip` and it worked.
I think you are missing librosa in the requirements.txt, I had to install it aswell in order to make it work

**Comment by ShmuelRonen** [comment]
where (in what file) are u replaced custom_nodes.facerestore_cf to custom_nodes.ComfyUI_wav2lip because I do it already?

**Comment by signorinileandro** [comment]
All of them. I was replacing one by one, but ComfyUI just kept giving error in all the places where `custom_nodes.facerestore_cf` was present

**Comment by ShmuelRonen** [comment]
I update now wav2lip.py and wav2lip_node.py

**Comment by signorinileandro** [comment]
Do u have an example workflow? Tried copying yours from the readme photo, but it gets stuck on Video Combine node

**Comment by ShmuelRonen** [comment]
video combine on your comfyui in out of date . git pull to the last version
