### ISSUE TITLE
unexpected EOF,i have download many wav2lip_gan.pth but all of them failed

### ISSUE THREAD

**Issue by whmc76** [ShmuelRonen/ComfyUI_wav2lip#39]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
(80, 279)
Length of mel chunks: 3
Load model from: E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
Load checkpoint from: E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\checkpoints\wav2lip_gan.pth
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
!!! Exception during processing!!! unexpected EOF, expected 3976502 more bytes. The file might be corrupted.
Traceback (most recent call last):
  File "E:\VIDEO\ComfyUI_video\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 104, in process
    out_img_list = wav2lip_(in_img_list, temp_audio_path, face_detect_batch, mode, model_path, framerate, lipsync_intensity, smoothing_factor)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\wav2lip_node.py", line 188, in wav2lip_
    for i, (img_batch, mel_batch, frames, coords) in enumerate(tqdm(gen,
  File "E:\VIDEO\ComfyUI_video\python_embeded\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\wav2lip_node.py", line 86, in datagen
    face_det_results = face_detect(frames, face_detect_batch)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\wav2lip_node.py", line 41, in face_detect
    detector = face_detection.FaceAlignment(face_detection.LandmarksType._2D,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\face_detection\api.py", line 60, in __init__
    self.face_detector = sfd.FaceDetector(device=device, verbose=verbose)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\ComfyUI\custom_nodes\ComfyUI_wav2lip\Wav2Lip\face_detection\detection\sfd\sfd_detector.py", line 22, in __init__
    model_weights = load_url(models_urls['s3fd'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\python_embeded\Lib\site-packages\torch\hub.py", line 770, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location, weights_only=weights_only)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\python_embeded\Lib\site-packages\torch\serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_video\python_embeded\Lib\site-packages\torch\serialization.py", line 1276, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 3976502 more bytes. The file might be corrupted.

**Comment by whmc76** [comment]
![image](https://github.com/user-attachments/assets/ac254fba-4b25-46a6-8248-3d69f853a92e)
search on huggingface i found 3 and they are the same size

**Comment by ShmuelRonen** [comment]
https://huggingface.co/Nekochu/Wav2Lip/resolve/main/wav2lip_gan.pth?download=true
