### ISSUE TITLE
Unable to find model wav2lip_gan.pth

### ISSUE THREAD

**Issue by start-life** [ShmuelRonen/ComfyUI_wav2lip#5]
Length of mel chunks: 984
Load checkpoint from: F:\Wav2Lip\checkpoints\wav2lip_gan.pth
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 179, in todo
    out_img_list = wav2lip_(in_img_list, temp_audio_path, face_detect_batch, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip\wav2lip_node.py", line 156, in wav2lip_
    model = load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip\wav2lip_node.py", line 122, in load_model
    checkpoint = _load(path)
                 ^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip\wav2lip_node.py", line 113, in _load
    checkpoint = torch.load(model_path)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Wav2Lip\\checkpoints\\wav2lip_gan.pth'

Prompt executed in 8.07 seconds

**Comment by ShmuelRonen** [comment]
Add path dynamic allocation to wav2lip.py please git pull

**Comment by ShmuelRonen** [comment]
New wav2lip.py please update
